FROM node:lts-alpine3.22

# WORKDIR /app

# COPY package*.json ./
# COPY . .

# RUN npm install --include=dev
EXPOSE 5173
COPY ./entrypointDev.sh /app/entrypointDev.sh
RUN chmod +x /app/entrypointDev.sh

ENTRYPOINT ["/app/entrypointDev.sh"]
#CMD ["npm", "run", "dev"]
