FROM node:lts-alpine3.22

RUN apk add --no-cache postgresql-client

# WORKDIR /app

# COPY package*.json ./
# COPY . .

COPY ./entrypointDev.sh /app/entrypointDev.sh
RUN chmod +x /app/entrypointDev.sh
EXPOSE 3000

ENTRYPOINT ["/app/entrypointDev.sh"]
